# Generated by Django 2.2 on 2021-01-04 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('498dcc01-8185-4d0e-a917-8a2a19023072')),
        ),
    ]
