# Generated by Django 2.2 on 2020-10-31 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('170cb47b-0e6b-4e4d-838c-8a5a4d66fe26')),
        ),
    ]
