# Generated by Django 2.2 on 2020-11-14 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('65e5a2e4-abbd-4897-a9a9-5b6caba42506')),
        ),
    ]
