# Generated by Django 2.2 on 2020-12-18 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201114_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('042767b2-d565-4f0a-a98c-9154739e0cdf')),
        ),
    ]
