# Generated by Django 2.2 on 2020-11-05 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201031_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('30073f3f-d478-4c29-b637-17e52a37d9c2')),
        ),
    ]
