# Generated by Django 2.2 on 2020-10-02 01:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201002_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasheddetails',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashkey',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c6d69631-ad79-4b6f-8fad-eafcfde26759')),
        ),
    ]
