# Generated by Django 2.2 on 2020-10-02 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201002_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasheddetails',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hashkey',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c8ae6363-c461-4e4c-b617-8c4c5ee587ab')),
        ),
    ]
