# Generated by Django 2.2 on 2021-01-04 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210104_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a0af5fdf-d350-4eba-a660-6d6317e478d8')),
        ),
    ]
