# Generated by Django 2.2 on 2020-11-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201105_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('8761c8c5-2f6f-4709-8bc6-261937cf09bd')),
        ),
        migrations.CreateModel(
            name='ArmenToForeignAccountTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='', max_length=40)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_account', models.CharField(max_length=22)),
                ('beneficiary_address', models.CharField(max_length=300)),
                ('beneficiary_branch_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('routing_number', models.PositiveIntegerField()),
                ('transfer_description', models.CharField(default='', max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArmenToArmenTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_account', models.CharField(default='', max_length=11)),
                ('amount', models.PositiveIntegerField()),
                ('transfer_description', models.CharField(default='', max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
