# Generated by Django 2.2 on 2021-01-02 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201218_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c98d3a01-6b45-4bcf-b930-ae6a0bc143dc')),
        ),
    ]
