# Generated by Django 2.2 on 2020-10-02 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201002_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('497758c0-5886-4f9a-8203-fc13c4d80503')),
        ),
    ]
