# Generated by Django 2.2 on 2021-02-14 11:51

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210104_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', help_text='Enter Full Name', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact Phone Number', max_length=128, region=None)),
                ('email', models.EmailField(max_length=50)),
                ('speak_with', models.CharField(choices=[('Support', 'Support'), ('Sales', 'Sales'), ('Abuse', 'Abuse'), ('Billing', 'Billing')], max_length=30)),
                ('reason_for_meeting', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('054811f6-23aa-4b60-a7f0-c9a33f1daf65')),
        ),
    ]
