# Generated by Django 2.2 on 2021-02-14 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210214_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='meeting_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('4b5299c8-441b-48df-9433-be332c15df52')),
        ),
    ]
