# Generated by Django 2.2 on 2021-02-14 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210214_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='meeting_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('74fca1b0-59ae-4194-b1fd-55d8c2fff04a')),
        ),
    ]
